---
name: VirtualChest
main: kim\present\virtualchest\VirtualChest
version: 1.1.11
api: [3.0.0, 3.0.0-ALPHA12, 4.0.0]
author: PresentKim
website: https://github.com/PresentKim/VirtualChest-PMMP
description: Give virtual chest to player
softdepend: [EconomyAPI, MathParserLib]

permissions:
  virtualchest.cmd:
    description: VirtualChest command
    default: true
    children:
      virtualchest.cmd.open:
        description: VirtualChest command - open
        default: true
      virtualchest.cmd.buy:
        description: VirtualChest command - buy
        default: true
      virtualchest.cmd.price:
        description: VirtualChest command - price
        default: op
      virtualchest.cmd.max:
        description: VirtualChest command - max
        default: op
      virtualchest.cmd.default:
        description: VirtualChest command - default
        default: op
      virtualchest.cmd.set:
        description: VirtualChest command - set
        default: op
      virtualchest.cmd.view:
        description: VirtualChest command - view
        default: op
...