# VirtualChest 플러그인을 위한 고급 설정 파일
# 이 설정들 중 일부는 안전하지만, 또 다른 것들은 잘못 수정했을 경우 서버에 오류가 발생할 수 있습니다
# 새로운 설정/기본은 이 파일을 업그레이드할 때 자동으로 나타나지 않습니다

settings:
  #다중 언어 설정
  #가능한 언어: eng, kor
  language: "kor"

  update-check: "false"


command:
  #메인 명령어의 이름
  #원하는대로 수정할 수 있습니다
  name: "virtualchest"

  #메인 명령어의 별칭들
  #원하는대로 추가, 수정, 삭제할 수 있습니다
  aliases: ["vc", "vchest"]

  children:
    #하위 명령어들의 설정
    #메인 명령어 설정과 동일합니다
    open:
      name: "Open"
      aliases: ["o"]
    buy:
      name: "Buy"
      aliases: ["b"]
    price:
      name: "Price"
      aliases: ["p"]
    max:
      name: "Max"
      aliases: ["m"]
    default:
      name: "Default"
      aliases: ["d"]
    set:
      name: "Set"
      aliases: ["s"]
    view:
      name: "View"
      aliases: ["v"]


permission:
  #메인 명령어의 권한
  #원하는대로 수정할 수 있습니다
  main: "true"

  children:
    #하위 명령어들의 권한
    #메인 명령어의 권한과 동일합니다
      open: "true"
      buy: "true"
      price: "op"
      max: "op"
      default: "op"
      set: "op"
      view: "op"