# HotBox 플러그인을 위한 고급 설정 파일
# 이 설정들 중 일부는 안전하지만, 또 다른 것들은 잘못 수정했을 경우 서버에 오류가 발생할 수 있습니다
# 새로운 설정/기본은 이 파일을 업그레이드할 때 자동으로 나타나지 않습니다

settings:
  #다중 언어 설정
  #가능한 언어: eng, kor
  language: "kor"

  update-check: "false"

  #보상 상자를 한번만 열 수 있게 할지 여부를 선택
  onetime-reward: "false"


command:
  #메인 명령어의 이름
  #원하는대로 수정할 수 있습니다
  name: "hotbox"

  #메인 명령어의 별칭들
  #원하는대로 추가, 수정, 삭제할 수 있습니다
  aliases: ["hb", "hottimebox"]

  children:
    #하위 명령어들의 설정
    #메인 명령어 설정과 동일합니다
    open:
      name: "Open"
      aliases: ["o"]
    edit:
      name: "Edit"
      aliases: ["e"]
    enable:
      name: "Enable"
      aliases: ["on", "start"]
    disable:
      name: "Disable"
      aliases: ["off", "stop"]


permission:
  #메인 명령어의 권한
  #원하는대로 수정할 수 있습니다
  main: "true"

  children:
    #하위 명령어들의 권한
    #메인 명령어의 권한과 동일합니다
    open: "true"
    edit: "op"
    enable: "op"
    disable: "op"