# Advanced configuration file for HotBox plugin
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading

settings:
  #Multi-language setting
  #Available: eng, kor
  language: "eng"

  update-check: "false"

  #Choose whether to allow open the reward box one time
  onetime-reward: "false"


command:
  #Name of main command
  #You can change this to be what you want
  name: "hotbox"

  #Aliases of main command
  #You can add, replace, or remove them as you like
  aliases: ["hb", "hottimebox"]

  children:
    #Setting of subcommands
    #Same as main command setting
    open:
      name: "Open"
      aliases: ["o"]
    edit:
      name: "Edit"
      aliases: ["e"]
    enable:
      name: "Enable"
      aliases: ["on", "start"]
    disable:
      name: "Disable"
      aliases: ["off", "stop"]


permission:
  #Permission of main command
  #You can change this to be what you want
  main: "true"

  children:
    #Permission of subcommands
    #Same as Permission of main command setting
    open: "true"
    edit: "op"
    enable: "op"
    disable: "op"